In [1]:
import tensorflow as tf
import sonnet as snt

print("TensorFlow version{}".format(tf.__version__))
print("Sonnet version{}".format(snt.__version__))

TensorFlow version2.17.0
Sonnet version2.0.3.dev


In [7]:
mlp = snt.Sequential([
	snt.Linear(102),

	tf.nn.relu,
	snt.Linear(5)
])

logits = mlp(tf.random.normal([2,5]))
print(logits)

tf.Tensor(
[[-0.4605936  -0.4463777  -0.12341459  0.37158337  0.24065322]
 [ 1.0382297  -0.10195427 -0.7811099  -0.05180255 -0.02293947]], shape=(2, 5), dtype=float32)


In [9]:
all_vars = mlp.variables
print(all_vars)

(<tf.Variable 'linear/b:0' shape=(102,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>, <tf.Variable 'linear/w:0' shape=(5, 102) dtype=float32, numpy=
array([[ 4.41370219e-01,  1.39202550e-01, -2.58777142e-01,
         2.84214199e-01,  2.18571395e-01,  2.53221571e-01,
         1.64625794e-01, -1.78333387e-01,  3.52673054e-01,
        -2.13743165e-01,  3.56748372e-01, -1.07673272e-01,
        -3.82390916e-01, -2.97559172e-01,  4.88011912e-02,
         1.44953936e-01, -1.88163102e-01,  2.35625729e-01,
         4.33759332e-01, -6.08457811e-02,  3.79

In [11]:
model_parameters = mlp.trainable_variables
print(model_parameters)

(<tf.Variable 'linear/b:0' shape=(102,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>, <tf.Variable 'linear/w:0' shape=(5, 102) dtype=float32, numpy=
array([[ 4.41370219e-01,  1.39202550e-01, -2.58777142e-01,
         2.84214199e-01,  2.18571395e-01,  2.53221571e-01,
         1.64625794e-01, -1.78333387e-01,  3.52673054e-01,
        -2.13743165e-01,  3.56748372e-01, -1.07673272e-01,
        -3.82390916e-01, -2.97559172e-01,  4.88011912e-02,
         1.44953936e-01, -1.88163102e-01,  2.35625729e-01,
         4.33759332e-01, -6.08457811e-02,  3.79

In [66]:
## Simple Reinforcement Learning
class SimpleReinforcedLearningModel(snt.Module):
	def __init__(self, action_size):
		super(SimpleReinforcedLearningModel, self).__init__()
		self._linear = snt.Linear(output_size=action_size)
	def __call__(self, state):
		return self._linear(state)

model = SimpleReinforcedLearningModel(action_size=4)
state = tf.random.normal([1,10])
action_probs = model(state)
print(action_probs)

tf.Tensor([[-1.7591031 -0.8732704  0.2321329  1.240978 ]], shape=(1, 4), dtype=float32)


In [ ]:
#CUstom Modal
class CustomConvLayer(snt.Module):
		def __init__(self, output_channels, kernel_shape):
			super(CustomConvLayer, self).__init__()
			self._conv = snt.Conv2D(output_channels, kernel_shape)
		
		def __call__(self, x):
			return self._conv(x)

conv_layer = CustomConvLayer(output_channels=32, kernel_shape=[3,3])
input_image = tf.random.normal([1,28,28,1])
output_image = conv_layer(input_image)
print(output_image)